apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  version: 1.16.1
  releaseName: cert-manager
  namespace: cert-manager
