apiVersion: v2
name: umbrella-chart-eso
description: A Helm chart for Kubernetes eso

type: application

version: 0.1.0

appVersion: "1.16.0"

dependencies:
  - name: external-secrets
    version: "0.10.3"
    repository: https://charts.external-secrets.io
